version: '3'
services:
  app:
    image: sohelamin/docker-swarm-example:latest
    ports:
      - "8080:8080"
    deploy:
      replicas: 3
  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - "9000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
